#!/usr/bin/env node
import crypto from 'node:crypto';
import { access, readFile, writeFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import path from 'node:path';
import { stdin as input, stdout as output } from 'node:process';
import { createInterface } from 'node:readline/promises';
import { fileURLToPath } from 'node:url';

const DEFAULT_TOPIC = 'vimo/devices/+/data';
const DEFAULT_LOCAL_BROKER = 'mqtt://localhost:1883';
const DEFAULT_HIVEMQ_PROTOCOL = 'mqtts';
const DEFAULT_HIVEMQ_PORT = '8883';

const args = process.argv.slice(2);
const forceOverwrite = hasFlag('force');
const nonInteractive = hasFlag('yes') || hasFlag('non-interactive');
const requestedBroker = normalizeBroker(getOptionValue('broker'));
const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const serverRoot = path.resolve(scriptDir, '..');
const defaultAppRoot = path.resolve(serverRoot, '..');
const configuredRoot = process.env.VIMO_ROOT?.trim();
const appRoot = path.resolve(configuredRoot || defaultAppRoot);
const outputPath = path.resolve(appRoot, getOptionValue('output') || '.env');

let rl;

main().catch((err) => {
    console.error(`Setup gagal: ${err.message}`);
    process.exit(1);
}).finally(() => {
    if (rl) {
        rl.close();
    }
});

async function main() {
    const existing = await loadExistingEnv(outputPath);
    const fileAlreadyExists = await fileExists(outputPath);

    if (fileAlreadyExists && !forceOverwrite) {
        if (nonInteractive) {
            throw new Error(`${path.basename(outputPath)} sudah ada. Jalankan lagi dengan --force jika ingin overwrite.`);
        }

        rl = createInterface({ input, output });
        const shouldOverwrite = await askYesNo(`File ${path.basename(outputPath)} sudah ada. Timpa file ini?`, false);

        if (!shouldOverwrite) {
            console.info('Setup dibatalkan.');
            return;
        }
    }

    if (!rl && !nonInteractive) {
        rl = createInterface({ input, output });
    }

    const broker = requestedBroker || await askBroker(existing.MQTT_PROVIDER || 'local');
    const nodeEnv = await resolveValue('NODE_ENV', existing.NODE_ENV || 'production');
    const appPort = await resolveValue('APP_PORT', existing.APP_PORT || existing.PORT || '3001');
    const apiKey = await resolveValue('API_KEY', existing.API_KEY || crypto.randomBytes(16).toString('hex'));
    const topic = await resolveValue('MQTT_TOPIC_SUBSCRIBE', existing.MQTT_TOPIC_SUBSCRIBE || DEFAULT_TOPIC);

    let lines = [
        '# Vimo Server Environment',
        '# Generated by scripts/setup-env.js',
        `NODE_ENV=${formatEnvValue(nodeEnv)}`,
        `APP_PORT=${formatEnvValue(appPort)}`,
        `API_KEY=${formatEnvValue(apiKey)}`,
        '',
        '# MQTT Configuration',
        `MQTT_PROVIDER=${formatEnvValue(broker)}`,
        `MQTT_TOPIC_SUBSCRIBE=${formatEnvValue(topic)}`,
        'MQTT_RECONNECT_PERIOD_MS=3000',
        'MQTT_CONNECT_TIMEOUT_MS=30000'
    ];

    if (broker === 'local') {
        const localUrl = await resolveValue(
            'MQTT_LOCAL_URL',
            existing.MQTT_LOCAL_URL || existing.MQTT_BROKER || DEFAULT_LOCAL_BROKER
        );

        lines = lines.concat([
            `MQTT_LOCAL_URL=${formatEnvValue(localUrl)}`,
            `MQTT_BROKER=${formatEnvValue(localUrl)}`,
            '',
            '# HiveMQ vars (isi jika MQTT_PROVIDER=hivemq)',
            'MQTT_HIVEMQ_PROTOCOL=mqtts',
            'MQTT_HIVEMQ_HOST=',
            'MQTT_HIVEMQ_PORT=8883',
            'MQTT_HIVEMQ_USERNAME=',
            'MQTT_HIVEMQ_PASSWORD=',
            'MQTT_HIVEMQ_CLIENT_ID=',
            'MQTT_HIVEMQ_REJECT_UNAUTHORIZED=true'
        ]);
    } else {
        const protocol = await resolveValue('MQTT_HIVEMQ_PROTOCOL', existing.MQTT_HIVEMQ_PROTOCOL || DEFAULT_HIVEMQ_PROTOCOL);
        const host = await resolveRequiredValue('MQTT_HIVEMQ_HOST', existing.MQTT_HIVEMQ_HOST || process.env.MQTT_HIVEMQ_HOST || '');
        const port = await resolveValue('MQTT_HIVEMQ_PORT', existing.MQTT_HIVEMQ_PORT || process.env.MQTT_HIVEMQ_PORT || DEFAULT_HIVEMQ_PORT);
        const username = await resolveRequiredValue(
            'MQTT_HIVEMQ_USERNAME',
            existing.MQTT_HIVEMQ_USERNAME || process.env.MQTT_HIVEMQ_USERNAME || ''
        );
        const password = await resolveRequiredValue(
            'MQTT_HIVEMQ_PASSWORD',
            existing.MQTT_HIVEMQ_PASSWORD || process.env.MQTT_HIVEMQ_PASSWORD || ''
        );
        const clientId = await resolveValue('MQTT_HIVEMQ_CLIENT_ID', existing.MQTT_HIVEMQ_CLIENT_ID || '');
        const rejectUnauthorized = await resolveValue(
            'MQTT_HIVEMQ_REJECT_UNAUTHORIZED',
            existing.MQTT_HIVEMQ_REJECT_UNAUTHORIZED || 'true'
        );

        lines = lines.concat([
            'MQTT_LOCAL_URL=mqtt://localhost:1883',
            'MQTT_BROKER=mqtt://localhost:1883',
            `MQTT_HIVEMQ_PROTOCOL=${formatEnvValue(protocol)}`,
            `MQTT_HIVEMQ_HOST=${formatEnvValue(host)}`,
            `MQTT_HIVEMQ_PORT=${formatEnvValue(port)}`,
            `MQTT_HIVEMQ_USERNAME=${formatEnvValue(username)}`,
            `MQTT_HIVEMQ_PASSWORD=${formatEnvValue(password)}`,
            `MQTT_HIVEMQ_CLIENT_ID=${formatEnvValue(clientId)}`,
            `MQTT_HIVEMQ_REJECT_UNAUTHORIZED=${formatEnvValue(rejectUnauthorized)}`
        ]);
    }

    await writeFile(outputPath, `${lines.join('\n')}\n`, 'utf8');

    const relativeToRoot = path.relative(appRoot, outputPath);
    const summaryPath = relativeToRoot && !relativeToRoot.startsWith('..') ? relativeToRoot : outputPath;
    console.info(`File ${summaryPath} berhasil dibuat.`);

    if (broker === 'local') {
        const localUrl = getValueFromLines(lines, 'MQTT_LOCAL_URL');
        console.info(`Broker aktif: local (${localUrl})`);
    } else {
        const protocol = getValueFromLines(lines, 'MQTT_HIVEMQ_PROTOCOL');
        const host = getValueFromLines(lines, 'MQTT_HIVEMQ_HOST');
        const port = getValueFromLines(lines, 'MQTT_HIVEMQ_PORT');
        console.info(`Broker aktif: HiveMQ (${protocol}://${host}:${port})`);
    }
}

async function fileExists(filePath) {
    try {
        await access(filePath, constants.F_OK);
        return true;
    } catch {
        return false;
    }
}

async function loadExistingEnv(filePath) {
    if (!(await fileExists(filePath))) {
        return {};
    }

    const raw = await readFile(filePath, 'utf8');
    const parsed = {};

    for (const rawLine of raw.split(/\r?\n/u)) {
        const line = rawLine.trim();
        if (!line || line.startsWith('#')) {
            continue;
        }

        const separatorIndex = line.indexOf('=');
        if (separatorIndex <= 0) {
            continue;
        }

        const key = line.slice(0, separatorIndex).trim();
        const value = line.slice(separatorIndex + 1).trim();
        parsed[key] = stripWrappingQuotes(value);
    }

    return parsed;
}

function stripWrappingQuotes(value) {
    if (!value) {
        return '';
    }

    const firstChar = value.at(0);
    const lastChar = value.at(-1);

    if ((firstChar === '"' && lastChar === '"') || (firstChar === '\'' && lastChar === '\'')) {
        return value.slice(1, -1);
    }

    return value;
}

function getOptionValue(name) {
    const prefix = `--${name}=`;
    const option = args.find((arg) => arg.startsWith(prefix));
    return option ? option.slice(prefix.length).trim() : '';
}

function hasFlag(name) {
    return args.includes(`--${name}`);
}

function normalizeBroker(value) {
    const normalized = value.trim().toLowerCase();

    if (!normalized) {
        return '';
    }

    if (normalized === 'local' || normalized === 'mosquitto') {
        return 'local';
    }

    if (normalized === 'hivemq') {
        return 'hivemq';
    }

    throw new Error('Nilai --broker harus "local" atau "hivemq".');
}

async function askBroker(defaultBroker) {
    const normalizedDefaultBroker = safeBroker(defaultBroker);

    if (nonInteractive) {
        return normalizedDefaultBroker;
    }

    console.info('');
    console.info('Pilih broker MQTT:');
    console.info('1. Local Mosquitto');
    console.info('2. HiveMQ Cloud');

    while (true) {
        const answer = (await rl.question(`Pilihan [1/2] (default: ${normalizedDefaultBroker}): `)).trim().toLowerCase();

        if (!answer) {
            return normalizedDefaultBroker;
        }

        if (answer === '1' || answer === 'local' || answer === 'mosquitto') {
            return 'local';
        }

        if (answer === '2' || answer === 'hivemq') {
            return 'hivemq';
        }

        console.info('Input tidak valid. Gunakan 1/local atau 2/hivemq.');
    }
}

function safeBroker(value) {
    try {
        return normalizeBroker(value || 'local') || 'local';
    } catch {
        return 'local';
    }
}

async function askYesNo(prompt, defaultValue) {
    if (nonInteractive) {
        return defaultValue;
    }

    const defaultHint = defaultValue ? 'Y/n' : 'y/N';
    const answer = (await rl.question(`${prompt} [${defaultHint}]: `)).trim().toLowerCase();

    if (!answer) {
        return defaultValue;
    }

    return answer === 'y' || answer === 'yes';
}

async function resolveValue(key, fallback) {
    if (nonInteractive) {
        return String(fallback ?? '').trim();
    }

    const prompt = `${key}${fallback ? ` [${fallback}]` : ''}: `;
    const answer = (await rl.question(prompt)).trim();

    if (!answer) {
        return String(fallback ?? '').trim();
    }

    return answer;
}

async function resolveRequiredValue(key, fallback) {
    const value = await resolveValue(key, fallback);

    if (value) {
        return value;
    }

    if (nonInteractive) {
        throw new Error(`${key} wajib diisi untuk broker HiveMQ.`);
    }

    console.info(`${key} tidak boleh kosong.`);
    return resolveRequiredValue(key, fallback);
}

function formatEnvValue(value) {
    const stringValue = String(value ?? '');

    if (!stringValue) {
        return '';
    }

    if (/[\s#"'`]/u.test(stringValue)) {
        return JSON.stringify(stringValue);
    }

    return stringValue;
}

function getValueFromLines(lines, key) {
    const row = lines.find((line) => line.startsWith(`${key}=`));
    if (!row) {
        return '';
    }

    return stripWrappingQuotes(row.slice(key.length + 1));
}
